export default {
  LOADING_PRODUCTS: 'LOADING_PRODUCTS',
  PRODUCTS_RECEIVED: 'PRODUCTS_RECEIVED',
  LOAD_PRODUCTS_FAILED: 'LOAD_PRODUCTS_FAILED',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART'
};
